spring:
  datasource:
    url: jdbc:mysql://localhost:33307/querydsl?serverTimezone=Asia/Seoul&characterEncoding=UTF8&autoCommit=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    sql: debug